<?php


namespace Frbit\Tests\Beelzebub\Sleeper;

use Frbit\Beelzebub\Helper\BuiltInDouble;
use Frbit\Beelzebub\Sleeper\EcoSleeper;
use Frbit\Tests\Beelzebub\TestCase;
use Mockery\MockInterface;

/**
 * @covers  \Frbit\Beelzebub\Sleeper\EcoSleeper
 * @package Frbit\Tests\Beelzebub\Sleeper
 **/
class EcoSleeperTest extends TestCase
{
    /**
     * @var MockInterface|BuiltInDouble
     */
    protected $builtIn;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->builtIn = $this->mock('\Frbit\Beelzebub\Helper\BuiltInDouble');
    }

    public function testSomething()
    {
        $sleeper = new EcoSleeper(0.5, 1.0, $this->builtIn);
        $start   = microtime(true);
        $this->builtIn->shouldReceive('time_sleep_until')
            ->atLeast(5)
            ->atMost(15)
            ->andReturnUsing(function ($time) use ($start) {
                $this->assertGreaterThanOrEqual($start, $time);
            });
        $sleeper->sleep(10);
    }

}